### PR TITLE
Use log.Fatalf instead of print + exit

### PR DESCRIPTION
**Pull request by prashantv**

### CODE REVIEW

**Comment by prashantv** [comment]
`log.Fatalf` cleans up the code a little, and is the usual way of exiting programs, e.g.:
https://github.com/golang/tools/blob/master/cmd/stringer/stringer.go
https://github.com/golang/tools/blob/master/cmd/godoc/main.go

`Fatal` is quite explicit in the name that it will exit, so why would you prefer a print + exit. Unless we have explicit exit codes to return, I'd say `Fatal` is clearer to read.

**Comment by peter-edge** [comment]
I really disagree - I don't like using Fatal at all. In the main function, I want to see explicitly that I am exiting with a non-zero status. I know others do this but I don't see the problem with explicitly calling a fmt.Print function and exiting. This also matters if I want to use a library like zap, for example - it's weird to have two logging libraries used when all I want to do is print an error in main and exit.

**Comment by prashantv** [comment]
Even if you were using zap, you should be using `Fatal` to exit from the main. `Fatal` should only ever be called from the main function, never from any library code (which should just return errors). But in the main function, the name makes it very clear that it exits with a non-zero exit.

Once you use `fmt.Println` you're doing a few more things manually: use `stderr`, make sure you add a newline if you do `Printf`, not lose the `os.Exit` call (I've seen cases where there's a print without an exit).

`os.Exit` makes stubbing out harder, while a `logger.Fatal` is easier to mock out in unit tests using a spy logger in zap for example.

Even if you disagree, I think consistency is more important, and our other binaries tend to use `log.Fatal`.

And it's not just our repos, here's an analysis of the cmd directory in the Go repo:
```
$ ag log.Fatal | grep -v _test.go | wc -l
     265

$ ag os.Exit | grep -v _test.go | wc -l
      81
```

`os.Exit` is used when they're either exiting with exit code 0, or get the exit code from some argument.

**Comment by peter-edge** [comment]
The go repo is just one example, of course it's mostly consistent. I don't see the big deal here - we have a style choice difference. I like that you explicitly see this is going to os.Stderr (zap/fx went to stdout for a while I think, I don't want that hidden under the food) and sometimes I don't want to just have an exit code of 1. We're not unit testing this main function, and I don't see when we would ever. This is why I usually use a do function to wrap the few things that happen in main.

**Comment by peter-edge** [comment]
One more thing - the length checking of args should really be in the do function. This is the pattern I usually use - main is just one call to do, and if there is an error, print it to stderr and exit 1.

**Comment by prashantv** [comment]
We should also be consistent in our own code too (similar to how the Go repo is consistent).

I'd like all all our code in the `uber-go` organization to be consistent, clear and high quality, no matter how small the project is.

`os.Exit` vs `Fatal` is not a big deal, but I've tried to explain why I think `Fatal` is better. Of course, we can have different opinions and disagree on which is better since it's subjective. However, consistency is important, especially when there's no agreement on which option is better, and we definitely prefer `log.Fatal` in thriftrw, and yarpc, so I'd prefer if we used that here too.

**Comment by peter-edge** [comment]
Ya, thats fine.

**Pull request merged**
